# Generated by Django 2.2.7 on 2019-11-10 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
