# Generated by Django 2.2.7 on 2019-11-17 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_auto_20191112_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataDateField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=55)),
                ('image_field', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='postdatatype',
            name='data_date_field',
            field=models.ManyToManyField(blank=True, to='community.DataDateField'),
        ),
    ]
