# Generated by Django 2.2.7 on 2019-11-17 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_auto_20191117_1246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datadatefield',
            old_name='image_field',
            new_name='date_field',
        ),
    ]
