# Generated by Django 2.2.7 on 2019-11-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20191117_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdatatype',
            name='name',
            field=models.CharField(blank=True, max_length=55),
        ),
    ]
