# Generated by Django 2.2.7 on 2019-11-19 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0009_postdatatype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdatatype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_type_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
