# Generated by Django 2.2.7 on 2019-11-21 22:11

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_postdatatype_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_template',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
