# Generated by Django 2.2.7 on 2019-11-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_posttemplate_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='description',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
