# Generated by Django 2.2.7 on 2019-11-26 13:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_posttemplate_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='template',
            new_name='post_template',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_text',
        ),
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
