# Generated by Django 2.2.7 on 2019-11-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_auto_20191126_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataFileField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('name', models.CharField(max_length=55)),
                ('text_field', models.FileField(max_length=55, upload_to='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
