# Generated by Django 2.2.7 on 2019-11-26 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_datafilefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafilefield',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Post'),
        ),
    ]
