# Generated by Django 2.2.7 on 2019-11-26 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20191126_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
