# Generated by Django 2.2.7 on 2019-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0021_auto_20191201_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='tags',
            field=models.ManyToManyField(related_name='post_template_tags', to='community.Tag'),
        ),
    ]
