# Generated by Django 2.2.7 on 2019-12-16 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0022_posttemplate_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='description',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
