# Generated by Django 2.2.7 on 2019-12-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0023_community_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=55),
        ),
    ]
