# Generated by Django 2.2.7 on 2020-04-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0024_auto_20191223_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='public_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='audio_version',
            field=models.FileField(max_length=55, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
