# Generated by Django 2.2.7 on 2020-05-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_auto_20200509_2312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='text',
        ),
    ]
