# Generated by Django 2.2.7 on 2020-05-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_auto_20200509_2314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='text',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
