# Generated by Django 2.2.7 on 2020-05-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_auto_20200510_1333'),
        ('community', '0029_auto_20200509_2320'),
    ]

    operations = [
    ]
