# Generated by Django 2.2.7 on 2020-05-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_merge_20200517_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttemplate',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
