# Generated by Django 2.2.7 on 2020-05-31 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_auto_20200531_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='flaggedUsers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='flags',
        ),
    ]
