# Generated by Django 2.2.7 on 2020-05-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_posttemplate_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttemplate',
            name='likes',
        ),
        migrations.AddField(
            model_name='post',
            name='flags',
            field=models.IntegerField(default=0),
        ),
    ]
