# Generated by Django 2.2.7 on 2020-05-19 09:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0032_auto_20200519_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flaggedUsers',
            field=models.ManyToManyField(related_name='flagged_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
