# Generated by Django 2.2.7 on 2020-05-19 09:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_post_flaggedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='flaggedUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
