# Generated by Django 2.2.7 on 2020-05-19 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0034_auto_20200519_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='denemeUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='flaggedUsers',
            field=models.ManyToManyField(related_name='flagged_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
