# Generated by Django 2.2.7 on 2020-05-19 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0035_auto_20200519_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='denemeUsers',
        ),
    ]
