# Generated by Django 2.2.7 on 2020-05-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_auto_20200531_1231'),
        ('community', '0036_remove_post_denemeusers'),
    ]

    operations = [
    ]
