# Generated by Django 2.2.7 on 2020-04-27 14:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='country',
            new_name='country_name',
        ),
        migrations.AddField(
            model_name='city',
            name='geolocation',
            field=models.CharField(default=datetime.datetime(2020, 4, 27, 14, 29, 51, 398483, tzinfo=utc), max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(default=datetime.datetime(2020, 4, 27, 14, 30, 2, 418014, tzinfo=utc), upload_to='media/city'),
            preserve_default=False,
        ),
    ]
