# Generated by Django 2.2.7 on 2020-05-01 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200427_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 7, 51, 4, 477621, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='modification_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 1, 7, 51, 10, 893626, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
