# Generated by Django 2.2.7 on 2020-05-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0006_city_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='creation_date',
            field=models.DateTimeField(editable=False),
        ),
        migrations.AlterField(
            model_name='city',
            name='modification_date',
            field=models.DateTimeField(editable=False),
        ),
    ]
