# Generated by Django 2.2.7 on 2020-05-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0008_auto_20200518_1321'),
        ('city', '0008_auto_20200518_1335'),
    ]

    operations = [
    ]
