# Generated by Django 2.2.7 on 2020-05-31 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0009_merge_20200518_1844'),
        ('city', '0009_merge_20200531_1144'),
    ]

    operations = [
    ]
