# Generated by Django 2.2.7 on 2020-06-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0010_merge_20200531_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/city'),
        ),
    ]
